# Workflow to validate your docs with oranda (and mdbook)
name: Web

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  web:
    name: Build and validate site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2

      - name: Install and run oranda
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/oranda/releases/latest/download/oranda-installer.sh | sh
          oranda build
      
      - name: Prepare HTML for link checking
        run: |
          mkdir -p /tmp/public/
          cp -R public /tmp/public/h5v

      - name: Check HTML for broken internal links
        uses: untitaker/hyperlink@0.1.29
        with:
          args: /tmp/public/
